app:
  title: Turbo
  secret: lQlYFGT5ZJBhsvZoQCf7qKBbWXtQ0FnnA7Wzsu6jtf8=
  description: Turbo
  copyright: Laam Ho
  allowRegistration: false
  TemplateDir: ""
  StaticDir: ""
  SyncLifetime: 10

database:
  driver: mysql
  user: root
  password:
  table: turbo
  host: localhost
  port: 3306

http:
  host: 127.0.0.1
  port: 5000