app:
  title: Turbo
  secret: lQlYFGT5ZJBhsvZoQCf7qKBbWXtQ0FnnA7Wzsu6jtf8=
  description: Turbo
  copyright: Laam Ho
  allowRegistration: false
  templateDir: template/views
  staticDir: template/static
  syncLifetime: 0

database:
  driver: mysql
  user: root
  password: a003120
  table: turbo
  host: localhost
  port: 3306

http:
  host: 127.0.0.1
  port: 5000