name: Build
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.6

      - name: Build project
        run: make build

      - name: Upload file to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: turbo
          path: |
            template/static/app.js
            template/static/app.css
            template/static/app.js.LICENSE.txt
            template/views/users.tmpl.html
            template/views/nodes.tmpl.html
            template/views/login.tmpl.html
            template/views/index.tmpl.html
            template/views/globals/header.tmpl.html
            template/views/globals/navbar.tmpl.html
            template/views/globals/footer.tmpl.html
            example/config.yml