name: Build
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.6

      - name: Get project dependencies
        run: go mod download

      - name: Build project
        run: make build

      - name: Create archive file
        shell: bash
        run: make archive

      - name: Upload file to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: turbo.tar.gz
          path: |
            ./output/turbo.tar.gz